# Generated by Django 3.1.8 on 2023-03-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestBank', '0008_auto_20230314_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
