# Generated by Django 3.1.8 on 2023-03-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestBank', '0008_useraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adress',
            new_name='address',
        ),
    ]
