# Generated by Django 3.1.8 on 2023-03-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestBank', '0009_client_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
