# Generated by Django 3.1.8 on 2023-03-13 15:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TestBank', '0009_auto_20230313_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientProfile',
            new_name='Client',
        ),
    ]
