# Generated by Django 3.1.8 on 2023-03-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestBank', '0010_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
    ]
