# Generated by Django 3.1.8 on 2023-03-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestBank', '0010_client_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_balance',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
