# Generated by Django 4.1.7 on 2023-03-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestBank', '0002_client_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not Selected')], default='N', max_length=1),
        ),
    ]
