# Generated by Django 4.1.7 on 2023-03-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestBank', '0003_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adress',
            field=models.CharField(default='N', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='N', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(default='N', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='zip_code',
            field=models.CharField(default='N', max_length=10),
        ),
    ]
